Phar: Phine\Phar\Stub Class Reference
Phine\Phar\Stub Class Reference
Generates a new PHP archive stub.
Public Member Functions
addRequire ($path, $internal=true)
Adds a file to require.
addSource ($source, $after=true)
Adds source code to embed.
getStub ()
Generates a stub according to the current settings.
interceptFileFuncs ($use=true)
Toggles the use of the Phar::interceptFileFuncs() method.
loadPhar ($file, $alias=null)
Adds an archive file to load.
mapPhar ($alias)
Sets the stream alias to map the archive to.
mount ($internal, $external)
Mounts an external path inside the archive.
mungServer (array $vars)
Sets the list of server variables to modify.
selfExtracting ($extract=true)
Toggles making the archive self extracting.
setBanner ($banner)
Sets the banner comment.
setShebang ($shebang)
Sets the shebang line.
webPhar ($alias=null, $index= 'index.php', $notFound=null, array $mime=array(), $rewrite=null)
Sets the settings for the Phar::webPhar() method.
Static Public Member Functions
static create ()
Creates a new stub generator.
Detailed Description
Generates a new PHP archive stub.
Author
Kevin Herrera kevin.nosp@m.@her.nosp@m.rera..nosp@m.io
Definition at line 12 of file Stub.php.
Member Function Documentation
Phine\Phar\Stub::addRequire ($path, $internal = true)
Adds a file to require.
Parameters
string $path The file path.
boolean $internal Is it an internal path?
Returns
Stub The stub generator.
Definition at line 99 of file Stub.php.
     {
         $this->require[] = array($path, $internal);
         return $this;
     }
Phine\Phar\Stub::addSource ($source, $after = true)
Adds source code to embed.
If $after is true, the source code will be embedded after all of the requires have been added to the stub. If it is false, it will be embedded before the requires.
Parameters
string $source The source code.
boolean $after Embed after the require(s)?
Returns
Stub The stub generator.
Definition at line 118 of file Stub.php.
     {
         $this->source[] = array($source, $after);
         return $this;
     }
static Phine\Phar\Stub::create () static
Creates a new stub generator.
Returns
Stub The new stub generator.
Definition at line 130 of file Stub.php.
     {
         return new self();
     }
Phine\Phar\Stub::getStub ()
Generates a stub according to the current settings.
Returns
string The generated stub.
Definition at line 140 of file Stub.php.
References Phine\Phar\Stub\Extract\from(), Phine\Phar\Stub\interceptFileFuncs(), Phine\Phar\Stub\loadPhar(), Phine\Phar\Stub\mapPhar(), Phine\Phar\Stub\mount(), Phine\Phar\Stub\mungServer(), and Phine\Phar\Stub\webPhar().
     {
         $stub = '';
         if ($this->shebang) {
             $stub = $this->shebang . "\n";
         }
         $stub .= "<?php\n\n";
         $export = function ($value) {
             return var_export($value, true);
         };
         if ($this->banner) {
             $stub .= sprintf(
                 "/*\n * %s\n */\n\n",
                 preg_replace(
                     '/\s+$/m',
                     '',
                     join("\n * ", explode("\n", $this->banner))
                 )
             );
         }
         if ($this->selfExtract) {
             $stub .= <<<STUB
 if (class_exists('Phar')) {
 \$include = 'phar://' . __FILE__;
 STUB;
         }
         if ($this->mapPhar) {
             $stub .= sprintf(
                 "Phar::mapPhar(%s);\n",
                 $export($this->mapPhar)
             );
         }
         if ($this->webPhar) {
             $stub .= sprintf(
                 "Phar::webPhar(%s, %s, %s, %s, %s);\n",
                 $export($this->webPhar[0]),
                 $export($this->webPhar[1]),
                 $export($this->webPhar[2]),
                 $export($this->webPhar[3]),
                 $export($this->webPhar[4])
             );
         }
         if ($this->interceptFileFuncs) {
             $stub .= "Phar::interceptFileFuncs();\n";
         }
         if ($this->mungServer) {
             $stub .= sprintf(
                 "Phar::mungServer(%s);\n",
                 $export($this->mungServer)
             );
         }
         foreach ($this->mount as $paths) {
             $stub .= sprintf(
                 "Phar::mount(%s, %s);\n",
                 $export($paths[0]),
                 $export($paths[1])
             );
         }
         foreach ($this->loadPhar as $phar) {
             $stub .= sprintf(
                 "Phar::loadPhar(%s, %s);\n",
                 $export($phar[0]),
                 $export($phar[1])
             );
         }
         if ($this->selfExtract) {
             $stub .= <<<STUB
 } else {
 \$include = Extract::from(__FILE__)->to();
 set_include_path(\$include . PATH_SEPARATOR . get_include_path());
 }
 STUB;
         }
         if ($this->source) {
             $stub .= "\n";
         }
         foreach ($this->source as $source) {
             if (!$source[1]) {
                 $stub .= "{$source[0]}\n";
             }
         }
         if ($this->require
             && ($this->mapPhar
                 || $this->webPhar
                 || $this->interceptFileFuncs
                 || $this->mungServer
                 || $this->mount
                 || $this->loadPhar)
         ) {
             $stub .= "\n";
         }
         foreach ($this->require as $file) {
             if ($file[1]) {
                 if (!preg_match('/^[\\\\\/]/', $file[0])) {
                     $file[0] = '/' . $file[0];
                 }
                 $file = '$include . ' . $export($file[0]);
             } else {
                 $file = $export($file[0]);
             }
             $stub .= "require $file;\n";
         }
         if ($this->source) {
             $stub .= "\n";
         }
         foreach ($this->source as $source) {
             if ($source[1]) {
                 $stub .= "{$source[0]}\n";
             }
         }
         if ($this->selfExtract) {
             $stub .= "\n" . trim(Embed::getSource()) . "\n";
         }
         $stub .= "\n__HALT_COMPILER();";
         return $stub;
     }
Phine\Phar\Stub::interceptFileFuncs ($use = true)
Toggles the use of the Phar::interceptFileFuncs() method.
Parameters
boolean $use Call the function?
Returns
Stub The stub generator.
Definition at line 288 of file Stub.php.
Referenced by Phine\Phar\Stub\getStub().
     {
         $this->interceptFileFuncs = $use;
         return $this;
     }
Phine\Phar\Stub::loadPhar ($file, $alias = null)
Adds an archive file to load.
Parameters
string $file The file path to the phar.
string $alias The stream alias for the phar.
Returns
Stub The stub generator.
Definition at line 303 of file Stub.php.
Referenced by Phine\Phar\Stub\getStub().
     {
         $this->loadPhar[] = array($file, $alias);
         return $this;
     }
Phine\Phar\Stub::mapPhar ($alias)
Sets the stream alias to map the archive to.
Parameters
string $alias The stream alias.
Returns
Stub The stub generator.
Definition at line 317 of file Stub.php.
Referenced by Phine\Phar\Stub\getStub().
     {
         $this->mapPhar = $alias;
         return $this;
     }
Phine\Phar\Stub::mount ($internal, $external)
Mounts an external path inside the archive.
Parameters
string $internal The internal path.
string $external The external path.
Returns
Stub The stub generator.
Definition at line 332 of file Stub.php.
Referenced by Phine\Phar\Stub\getStub().
     {
         $this->mount[] = array($internal, $external);
         return $this;
     }
Phine\Phar\Stub::mungServer (array $vars)
Sets the list of server variables to modify.
Parameters
array $vars The list of variables.
Returns
Stub The stub generator.
Definition at line 346 of file Stub.php.
Referenced by Phine\Phar\Stub\getStub().
     {
         $this->mungServer = $vars;
         return $this;
     }
Phine\Phar\Stub::selfExtracting ($extract = true)
Toggles making the archive self extracting.
Parameters
boolean $extract Make archive self extracting?
Returns
Stub The stub generator.
Definition at line 360 of file Stub.php.
     {
         $this->selfExtract = $extract;
         return $this;
     }
Phine\Phar\Stub::setBanner ($banner)
Sets the banner comment.
Parameters
string $banner The comment.
Returns
Stub The stub generator.
Definition at line 374 of file Stub.php.
     {
         $this->banner = $banner;
         return $this;
     }
Phine\Phar\Stub::setShebang ($shebang)
Sets the shebang line.
Parameters
string $shebang The shebang line.
Returns
Stub The stub generator.
Definition at line 388 of file Stub.php.
     {
         $this->shebang = $shebang;
         return $this;
     }
Phine\Phar\Stub::webPhar ($alias = null, $index = 'index.php', $notFound = null, array $mime = array(), $rewrite = null)
Sets the settings for the Phar::webPhar() method.
Parameters
string $alias The stream alias.
string $index The index internal file path.
string $notFound The 404 internal file path.
array $mime The list of file extension to MIME types.
string $rewrite The name of the rewrite function.
Returns
Stub The stub generator.
Definition at line 406 of file Stub.php.
Referenced by Phine\Phar\Stub\getStub().
       {
         $this->webPhar = array($alias, $index, $notFound, $mime, $rewrite);
         return $this;
     }
The documentation for this class was generated from the following file:
Stub.php