Phar: Phine\Phar\Signature\Algorithm\SHA1 Class Reference
Phine\Phar\Signature\Algorithm\SHA1 Class Reference
Provides support for the SHA1 algorithm.
Public Member Functions
getFlag ()
Returns the signature algorithm flag.
Returns
integer The signature algorithm flag.
readSignature (Reader $reader)
Reads the signature from the archive file.
Parameters
Reader $reader The archive file reader.
verifySignature (Reader $reader)
Verifies the signature for the archive file.
Parameters
Reader $reader The archive file reader.
Returns
boolean Returns true if verified, false if not.
Protected Member Functions
getAlgorithm ()
getName ()
getSize ()
Detailed Description
Provides support for the SHA1 algorithm.
Author
Kevin Herrera kevin.nosp@m.@her.nosp@m.rera..nosp@m.io
Definition at line 10 of file SHA1.php.
Member Function Documentation
Phine\Phar\Signature\Algorithm\SHA1::getAlgorithm () protected
Definition at line 23 of file SHA1.php.
     {
         return 'sha1';
     }
Phine\Phar\Signature\Algorithm\SHA1::getFlag ()
Returns the signature algorithm flag.
Returns
integer The signature algorithm flag.
Implements Phine\Phar\Signature\Algorithm\AlgorithmInterface.
Definition at line 15 of file SHA1.php.
     {
         return 0x02;
     }
Phine\Phar\Signature\Algorithm\SHA1::getName () protected
Definition at line 31 of file SHA1.php.
     {
         return 'SHA-1';
     }
Phine\Phar\Signature\Algorithm\SHA1::getSize () protected
Definition at line 39 of file SHA1.php.
     {
         return 20;
     }
Phine\Phar\Signature\Algorithm\AbstractHashAlgorithm::readSignature (Reader $reader) inherited
Reads the signature from the archive file.
Parameters
Reader $reader The archive file reader.
Implements Phine\Phar\Signature\Algorithm\AlgorithmInterface.
Definition at line 17 of file AbstractHashAlgorithm.php.
References Phine\Phar\Signature\Algorithm\AbstractHashAlgorithm\getName(), Phine\Phar\Signature\Algorithm\AbstractHashAlgorithm\getSize(), Phine\Phar\File\Reader\read(), and Phine\Phar\File\Reader\seek().
Referenced by Phine\Phar\Signature\Algorithm\AbstractHashAlgorithm\verifySignature().
     {
         $size = $this->getSize();
         $reader->seek(-8 - $size, SEEK_END);
         $hash = unpack('H*', $reader->read($size));
         $hash = strtoupper($hash[1]);
         return array(
             'hash' => $hash,
             'hash_type' => $this->getName()
         );
     }
Phine\Phar\Signature\Algorithm\AbstractHashAlgorithm::verifySignature (Reader $reader) inherited
Verifies the signature for the archive file.
Parameters
Reader $reader The archive file reader.
Returns
boolean Returns true if verified, false if not.
Implements Phine\Phar\Signature\Algorithm\AlgorithmInterface.
Definition at line 35 of file AbstractHashAlgorithm.php.
References Phine\Phar\Signature\Algorithm\AbstractHashAlgorithm\getAlgorithm(), Phine\Phar\File\Reader\getHandle(), Phine\Phar\Signature\Algorithm\AbstractHashAlgorithm\getSize(), Phine\Phar\File\Reader\getSize(), Phine\Phar\Signature\Algorithm\AbstractHashAlgorithm\readSignature(), and Phine\Phar\File\Reader\seek().
     {
         $expected = $this->readSignature($reader);
         $context = hash_init($this->getAlgorithm());
         $reader->seek(0);
         hash_update_stream(
             $context,
             $reader->getHandle(),
             $reader->getSize() - $this->getSize() - 8
         );
         $actual = strtoupper(hash_final($context));
         return ($expected['hash'] === $actual);
     }
The documentation for this class was generated from the following file:
SHA1.php