Phar: Phine\Phar\Manifest Class Reference
Phine\Phar\Manifest Class Reference
Reads the manifest of a PHP archive file.
Public Member Functions
__construct (Reader $reader, $offset=null)
Sets the PHP archive file reader and manifest offset.
getAlias ()
Returns the stream alias.
getAliasSize ()
Returns the size of the stream alias in bytes.
getApiVersion ()
Returns the API version of the manifest.
getFileCount ()
Returns the number of files listed in the manifest.
getFileList ()
Returns the list of files in the manifest.
getGlobalFlags ()
Returns the global bitmapped flags in the manifest.
getMetadata ()
Return the unserialized metadata of the manifest.
getMetadataSize ()
Returns the size of the metadata in bytes.
getOffset ()
Returns the byte offset of the manifest.
getReader ()
Returns the archive file reader.
getSize ()
Returns the size of the manifest in bytes.
Static Public Member Functions
static findOffset (Reader $reader)
Finds the manifest offset of an archive.
Public Attributes
const BZ2 = 0x2000
const GZ = 0x1000
const MASK = 0x3000
Detailed Description
Reads the manifest of a PHP archive file.
Author
Kevin Herrera kevin.nosp@m.@her.nosp@m.rera..nosp@m.io
Definition at line 15 of file Manifest.php.
Constructor & Destructor Documentation
Phine\Phar\Manifest::__construct (Reader $reader, $offset = null)
Sets the PHP archive file reader and manifest offset.
If an offset is not provided findOffset() is called to discover the offset.
Parameters
Reader $reader The archive file reader.
integer $offset The manifest offset.
Exceptions
ManifestException If the offset is not set and no offset could be found using the given archive reader.
Definition at line 75 of file Manifest.php.
References Phine\Phar\File\Reader\getFile(), and Phine\Phar\Exception\ManifestException\offsetNotFound().
     {
         if (null === $offset) {
             if (null === ($offset = self::findOffset($reader))) {
                 throw ManifestException::offsetNotFound($reader->getFile());
             }
         }
         $this->offset = $offset;
         $this->reader = $reader;
     }
Member Function Documentation
static Phine\Phar\Manifest::findOffset (Reader $reader) static
Finds the manifest offset of an archive.
Parameters
Reader $reader The archive file reader.
Returns
integer If the manifest offset is found, it is returned. If a manifest offset is not found, null is returned.
Definition at line 95 of file Manifest.php.
References Phine\Phar\File\Reader\getPosition(), Phine\Phar\File\Reader\isEndOfFile(), Phine\Phar\File\Reader\read(), and Phine\Phar\File\Reader\seek().
     {
         $reader->seek(0);
         $offset = 0;
         while (!$reader->isEndOfFile()) {
             if (strtolower($reader->read(1)) === self::$sequence[$offset]) {
                 $offset++;
             } else {
                 $offset = 0;
             }
             if (!isset(self::$sequence[$offset + 1])) {
                 break;
             }
         }
         $reader->seek(1, SEEK_CUR);
         if ($offset === (count(self::$sequence) - 1)) {
             $position = $reader->getPosition();
             if ("\r\n" === $reader->read(2)) {
                 return $position + 2;
             }
             return $position;
         }
         return null;
     }
Phine\Phar\Manifest::getAlias ()
Returns the stream alias.
Returns
string The alias in the manifest.
Definition at line 133 of file Manifest.php.
References Phine\Phar\Manifest\getAliasSize().
     {
         if (0 < ($size = $this->getAliasSize())) {
             return $this->reader->read($size);
         }
         return null;
     }
Phine\Phar\Manifest::getAliasSize ()
Returns the size of the stream alias in bytes.
Returns
integer The size of the alias in bytes.
Definition at line 147 of file Manifest.php.
Referenced by Phine\Phar\Manifest\getAlias(), Phine\Phar\Manifest\getFileList(), and Phine\Phar\Manifest\getMetadataSize().
     {
         $this->reader->seek($this->offset + 14);
         return $this->readLong();
     }
Phine\Phar\Manifest::getApiVersion ()
Returns the API version of the manifest.
Returns
string The API version of the manifest.
Definition at line 159 of file Manifest.php.
     {
         $this->reader->seek($this->offset + 8);
         $version = unpack('H*', $this->reader->read(2));
         $version = hexdec($version[1]);
         // @codeCoverageIgnoreStart
         $version = sprintf(
             '%u.%u.%u',
             $version >> 12,
             ($version >> 8) & 0xF,
             ($version >> 4) & 0xF
         );
         // @codeCoverageIgnoreEnd
         return $version;
     }
Phine\Phar\Manifest::getFileCount ()
Returns the number of files listed in the manifest.
Returns
integer The number of files in the manifest.
Definition at line 183 of file Manifest.php.
Referenced by Phine\Phar\Manifest\getFileList().
     {
         $this->reader->seek($this->offset + 4);
         return $this->readLong();
     }
Phine\Phar\Manifest::getFileList ()
Returns the list of files in the manifest.
Returns
FileInfo[] The list of files in the manifest.
Definition at line 195 of file Manifest.php.
References Phine\Phar\Manifest\getAliasSize(), Phine\Phar\Manifest\getFileCount(), Phine\Phar\Manifest\getMetadataSize(), and Phine\Phar\Manifest\getSize().
     {
         $count = $this->getFileCount();
         $size = $this->getSize() + 4;
         $this->reader->seek(
             $this->offset
             + 18
             + $this->getAliasSize()
             + 4
             + $this->getMetadataSize()
         );
         return $this->readFileList($count, $size);
     }
Phine\Phar\Manifest::getGlobalFlags ()
Returns the global bitmapped flags in the manifest.
Returns
integer The global bitmapped flags.
Definition at line 217 of file Manifest.php.
     {
         $this->reader->seek($this->offset + 10);
         return $this->readLong() & self::MASK;
     }
Phine\Phar\Manifest::getMetadata ()
Return the unserialized metadata of the manifest.
Returns
mixed The unserialized metadata.
Exceptions
ManifestException If the metadata is corrupt or invalid.
Definition at line 241 of file Manifest.php.
References Phine\Phar\Manifest\getMetadataSize().
     {
         if (0 === ($size = $this->getMetadataSize())) {
             return null;
         }
         return $this->readData($size);
     }
Phine\Phar\Manifest::getMetadataSize ()
Returns the size of the metadata in bytes.
Returns
integer The size of the metadata in bytes.
Definition at line 255 of file Manifest.php.
References Phine\Phar\Manifest\getAliasSize().
Referenced by Phine\Phar\Manifest\getFileList(), and Phine\Phar\Manifest\getMetadata().
     {
         $this->reader->seek($this->offset + 18 + $this->getAliasSize());
         return $this->readLong();
     }
Phine\Phar\Manifest::getOffset ()
Returns the byte offset of the manifest.
Returns
integer The byte offset.
Definition at line 229 of file Manifest.php.
     {
         return $this->offset;
     }
Phine\Phar\Manifest::getReader ()
Returns the archive file reader.
Returns
Reader The archive file reader.
Definition at line 267 of file Manifest.php.
     {
         return $this->reader;
     }
Phine\Phar\Manifest::getSize ()
Returns the size of the manifest in bytes.
Returns
integer The size of the manifest in bytes.
Definition at line 277 of file Manifest.php.
Referenced by Phine\Phar\Manifest\getFileList().
     {
         $this->reader->seek($this->offset);
         return $this->readLong();
     }
The documentation for this class was generated from the following file:
Manifest.php