Phar: Phine\Phar\File\Reader Class Reference
Phine\Phar\File\Reader Class Reference
Manages strict file reading operations.
Public Member Functions
__construct ($file)
Sets the path of the file for reading.
__destruct ()
Closes the file if it's open.
getFile ()
Returns the path of the file.
getHandle ()
Returns the reading file handle.
getPosition ()
Returns the current position of the file pointer.
getSize ()
Returns the size of the file.
isEndOfFile ()
Checks if the end of the file has been reached.
read ($bytes)
Reads a specific number of bytes from the file.
seek ($offset, $whence=SEEK_SET)
Seeks to a specific point in the file.
Detailed Description
Manages strict file reading operations.
Author
Kevin Herrera kevin.nosp@m.@her.nosp@m.rera..nosp@m.io
Definition at line 13 of file Reader.php.
Constructor & Destructor Documentation
Phine\Phar\File\Reader::__construct ($file)
Sets the path of the file for reading.
Parameters
string $file The path of the file.
Exceptions
Exception
FileException If the file path is not valid.
Definition at line 37 of file Reader.php.
     {
         if (!is_file($file)) {
             throw FileException::createUsingFormat(
                 'The path "%s" is not a file or does not exist.',
                 $file
             );
         }
         $this->file = $file;
     }
Phine\Phar\File\Reader::__destruct ()
Closes the file if it's open.
Definition at line 52 of file Reader.php.
     {
         if ($this->handle) {
             fclose($this->handle);
         }
     }
Member Function Documentation
Phine\Phar\File\Reader::getFile ()
Returns the path of the file.
Returns
string The path of the file.
Definition at line 64 of file Reader.php.
Referenced by Phine\Phar\Manifest\__construct().
     {
         return $this->file;
     }
Phine\Phar\File\Reader::getHandle ()
Returns the reading file handle.
Returns
resource The file handle.
Exceptions
Exception
FileException If the file could not be opened for reading.
Definition at line 77 of file Reader.php.
Referenced by Phine\Phar\File\Reader\getPosition(), Phine\Phar\File\Reader\isEndOfFile(), Phine\Phar\File\Reader\read(), Phine\Phar\File\Reader\seek(), and Phine\Phar\Signature\Algorithm\AbstractHashAlgorithm\verifySignature().
     {
         if (null === $this->handle) {
             if (false === ($this->handle = @fopen($this->file, 'rb'))) {
                 throw FileException::createUsingLastError();
             }
         }
         return $this->handle;
     }
Phine\Phar\File\Reader::getPosition ()
Returns the current position of the file pointer.
Returns
integer The current position.
Exceptions
Exception
FileException If the size could not be read.
Definition at line 96 of file Reader.php.
References Phine\Phar\File\Reader\getHandle().
Referenced by Phine\Phar\Manifest\findOffset().
     {
         if (false === ($position = @ftell($this->getHandle()))) {
             throw FileException::createUsingLastError();
         }
         return $position;
     }
Phine\Phar\File\Reader::getSize ()
Returns the size of the file.
Returns
integer The size of the file.
Exceptions
Exception
FileException If the size could not be read.
Definition at line 113 of file Reader.php.
Referenced by Phine\Phar\Signature\Algorithm\AbstractHashAlgorithm\verifySignature().
     {
         if (false === ($size = @filesize($this->file))) {
             throw FileException::createUsingLastError();
         }
         return $size;
     }
Phine\Phar\File\Reader::isEndOfFile ()
Checks if the end of the file has been reached.
Before feof() is called, an attempt is made to reach a single byte from the file. If the read fails, then the feof() is made to actually determine the if the end of the file has been reached. If the EOF is not reached, the file handle will be seeked back the one byte that was read.
Returns
boolean If the end of the file has been reached, false is returned. If the end of the file has not been reached, true is returned.
Definition at line 134 of file Reader.php.
References Phine\Phar\File\Reader\getHandle().
Referenced by Phine\Phar\Manifest\findOffset(), and Phine\Phar\File\Reader\read().
     {
         $handle = $this->getHandle();
         if (false === @fgetc($handle)) {
             return feof($handle);
         } else {
             fseek($handle, -1, SEEK_CUR);
         }
         return false;
     }
Phine\Phar\File\Reader::read ($bytes)
Reads a specific number of bytes from the file.
Parameters
integer $bytes The number of bytes.
Returns
string The bytes read.
Exceptions
Exception
FileException If not all the bytes were read.
Definition at line 158 of file Reader.php.
References Phine\Phar\File\Reader\getHandle(), and Phine\Phar\File\Reader\isEndOfFile().
Referenced by Phine\Phar\Manifest\findOffset(), Phine\Phar\Signature\Algorithm\AbstractHashAlgorithm\readSignature(), and Phine\Phar\Signature\Algorithm\OpenSSL\readSignature().
     {
         $read = '';
         $total = $bytes;
         while (!$this->isEndOfFile() && $bytes) {
             if (false === ($chunk = @fread($this->getHandle(), $bytes))) {
                 throw FileException::createUsingLastError();
             }
             $read .= $chunk;
             $bytes -= strlen($chunk);
         }
         if ($total !== ($actual = strlen($read))) {
             throw FileException::createUsingFormat(
                 'Only read %d bytes of %d from "%s".',
                 $actual,
                 $total,
                 $this->file
             );
         }
         return $read;
     }
Phine\Phar\File\Reader::seek ($offset, $whence = SEEK_SET)
Seeks to a specific point in the file.
Parameters
integer $offset The offset.
integer $whence The direction.
Exceptions
Exception
FileException If seeking failed.
Definition at line 193 of file Reader.php.
References Phine\Phar\File\Reader\getHandle().
Referenced by Phine\Phar\Manifest\findOffset(), Phine\Phar\Signature\Algorithm\AbstractHashAlgorithm\readSignature(), Phine\Phar\Signature\Algorithm\OpenSSL\readSignature(), and Phine\Phar\Signature\Algorithm\AbstractHashAlgorithm\verifySignature().
     {
         if (-1 === @fseek($this->getHandle(), $offset, $whence)) {
             throw FileException::createUsingFormat(
                 'Could not seek to %d in "%s".',
                 $offset,
                 $this->file
             );
         }
     }
The documentation for this class was generated from the following file:
Reader.php