Phar: Phine\Phar\Extract Class Reference
Phine\Phar\Extract Class Reference
Extracts the contents of an archive.
Public Member Functions
__construct (Manifest $manifest)
Sets the archive manifest.
extractTo ($dir, $filter=null)
Extracts one or more files to an output directory.
getManifest ()
Returns the manifest for the archive file.
Static Public Member Functions
static extractFile (FileInfo $file)
Returns the contents of a file from the manifest.
Detailed Description
Extracts the contents of an archive.
Author
Kevin Herrera kevin.nosp@m.@her.nosp@m.rera..nosp@m.io
Definition at line 15 of file Extract.php.
Constructor & Destructor Documentation
Phine\Phar\Extract::__construct (Manifest $manifest)
Sets the archive manifest.
Parameters
Manifest $manifest The archive manifest.
Definition at line 36 of file Extract.php.
     {
         $this->manifest = $manifest;
     }
Member Function Documentation
static Phine\Phar\Extract::extractFile (FileInfo $file) static
Returns the contents of a file from the manifest.
Parameters
FileInfo $file The file information from the manifest.
Returns
string The decompressed file contents.
Exceptions
Exception
FileException If the file could not be decompressed.
Definition at line 51 of file Extract.php.
References Phine\Phar\Manifest\FileInfo\getCompressedSize(), Phine\Phar\Manifest\FileInfo\getManifest(), Phine\Phar\Manifest\FileInfo\getName(), Phine\Phar\Manifest\FileInfo\getOffset(), and Phine\Phar\Manifest\FileInfo\isCompressed().
     {
         if (null === self::$compression) {
             self::$compression = array(
                 'bzip2' => function_exists('bzdecompress'),
                 'gzip' => function_exists('gzinflate'),
             );
         }
         $reader = $file->getManifest()->getReader();
         $reader->seek($file->getOffset());
         $contents = $reader->read($file->getCompressedSize());
         if ($file->isCompressed(Manifest::BZ2)) {
             if (!self::$compression['bzip2']) {
                 throw FileException::createUsingFormat(
                     'The "bz2" extension is required to decompress "%s".',
                     $file->getName()
                 );
             }
             $contents = bzdecompress($contents);
         } elseif ($file->isCompressed(Manifest::GZ)) {
             if (!self::$compression['gzip']) {
                 throw FileException::createUsingFormat(
                     'The "zlib" extension is required to decompress "%s".',
                     $file->getName()
                 );
             }
             $contents = gzinflate($contents);
         }
         return $contents;
     }
Phine\Phar\Extract::extractTo ($dir, $filter = null)
Extracts one or more files to an output directory.
If a $filter callable is provided, it will be called with each file found in the archive. If true is returned by the filter, the file will not be extracted. If any other value is returned, the file will be extracted.
Parameters
string $dir The output directory path.
callable $filter The callable used to filter files.
Returns
integer The number of files extracted.
Exceptions
Exception
FileException If a file could not be extracted.
Definition at line 105 of file Extract.php.
     {
         $files = $this->manifest->getFileList();
         $count = 0;
         foreach ($files as $file) {
             if ($filter && (true === $filter($file))) {
                 continue;
             }
             $path = $dir . '/' . $file->getName();
             $base = dirname($path);
             if (!is_dir($base)) {
                 if (!@mkdir($base, 0755, true)) {
                     throw FileException::createUsingLastError();
                 }
             }
             $writer = new Writer($path);
             $writer->write(self::extractFile($file));
             $count++;
         }
         return $count;
     }
Phine\Phar\Extract::getManifest ()
Returns the manifest for the archive file.
Returns
Manifest The manifest for the archive file.
Definition at line 138 of file Extract.php.
     {
         return $this->manifest;
     }
The documentation for this class was generated from the following file:
Extract.php