Phar: Phine\Phar\Signature Class Reference
Phine\Phar\Signature Class Reference
Reads and verifies an archive's signature without the phar extension.
Public Member Functions
__construct (Reader $reader)
Sets the archive file reader.
addAlgorithm (AlgorithmInterface $algorithm)
Adds a signature algorithm to recognize.
getAlgorithm ()
Returns the algorithm used for the archive file.
getSignature ()
Returns the signature stored in the archive file.
verifySignature ()
Verifies the signature of the archive file.
Static Public Member Functions
static create ($file)
Creates a new instance with default algorithms registered.
Detailed Description
Reads and verifies an archive's signature without the phar extension.
Author
Kevin Herrera kevin.nosp@m.@her.nosp@m.rera..nosp@m.io
Definition at line 16 of file Signature.php.
Constructor & Destructor Documentation
Phine\Phar\Signature::__construct (Reader $reader)
Sets the archive file reader.
Parameters
Reader $reader The archive file reader.
Definition at line 44 of file Signature.php.
     {
         $this->reader = $reader;
     }
Member Function Documentation
Phine\Phar\Signature::addAlgorithm (AlgorithmInterface $algorithm)
Adds a signature algorithm to recognize.
Parameters
AlgorithmInterface $algorithm An algorithm.
Definition at line 54 of file Signature.php.
     {
         $this->algorithms[spl_object_hash($algorithm)] = $algorithm;
     }
static Phine\Phar\Signature::create ($file) static
Creates a new instance with default algorithms registered.
Parameters
Reader | string $file The archive file path or reader.
Returns
Signature The new instance.
Definition at line 66 of file Signature.php.
     {
         if (is_string($file)) {
             $file = new Reader($file);
         }
         $signature = new self($file);
         $signature->addAlgorithm(new Algorithm\MD5());
         $signature->addAlgorithm(new Algorithm\SHA1());
         $signature->addAlgorithm(new Algorithm\SHA256());
         $signature->addAlgorithm(new Algorithm\SHA512());
         $signature->addAlgorithm(new Algorithm\OpenSSL());
         return $signature;
     }
Phine\Phar\Signature::getAlgorithm ()
Returns the algorithm used for the archive file.
Returns
AlgorithmInterface The algorithm.
Exceptions
Exception
SignatureException If the algorithm could not be found.
Definition at line 90 of file Signature.php.
Referenced by Phine\Phar\Signature\getSignature(), and Phine\Phar\Signature\verifySignature().
     {
         if (null === $this->algorithm) {
             $this->reader->seek(-4, SEEK_END);
             if ('GBMB' !== $this->reader->read(4)) {
                 throw SignatureException::createUsingFormat(
                     'The archive "%s" is not signed.',
                     $this->reader->getFile()
                 );
             }
             $this->reader->seek(-8, SEEK_END);
             $flag = unpack('V', $this->reader->read(4));
             $flag = (int) $flag[1];
             foreach ($this->algorithms as $algorithm) {
                 if ($flag === $algorithm->getFlag()) {
                     $this->algorithm = $algorithm;
                 }
             }
             if (null === $this->algorithm) {
                 throw SignatureException::createUsingFormat(
                     'The algorithm for the archive "%s" is not supported.',
                     $this->reader->getFile()
                 );
             }
         }
         return $this->algorithm;
     }
Phine\Phar\Signature::getSignature ()
Returns the signature stored in the archive file.
Returns
array The signature.
Definition at line 129 of file Signature.php.
References Phine\Phar\Signature\getAlgorithm().
     {
         return $this->getAlgorithm()->readSignature($this->reader);
     }
Phine\Phar\Signature::verifySignature ()
Verifies the signature of the archive file.
Returns
boolean Returns true if verified, false if not.
Definition at line 139 of file Signature.php.
References Phine\Phar\Signature\getAlgorithm().
     {
         return $this->getAlgorithm()->verifySignature($this->reader);
     }
The documentation for this class was generated from the following file:
Signature.php