Phar: Phine\Phar\Signature\Algorithm\OpenSSL Class Reference
Phine\Phar\Signature\Algorithm\OpenSSL Class Reference
Provides support for OpenSSL signed archives.
Public Member Functions
__construct ()
Throws an exception if the openssl extension is not available.
getFlag ()
Returns the signature algorithm flag.
Returns
integer The signature algorithm flag.
readSignature (Reader $reader)
Reads the signature from the archive file.
Parameters
Reader $reader The archive file reader.
verifySignature (Reader $reader)
Verifies the signature for the archive file.
Parameters
Reader $reader The archive file reader.
Returns
boolean Returns true if verified, false if not.
Detailed Description
Provides support for OpenSSL signed archives.
Author
Kevin Herrera kevin.nosp@m.@her.nosp@m.rera..nosp@m.io
Definition at line 15 of file OpenSSL.php.
Constructor & Destructor Documentation
Phine\Phar\Signature\Algorithm\OpenSSL::__construct ()
Throws an exception if the openssl extension is not available.
Exceptions
SignatureException If the extension is not available.
Definition at line 22 of file OpenSSL.php.
     {
         if (!extension_loaded('openssl')) {
             throw new SignatureException(
                 'The "openssl" extension is not installed.'
             );
         }
     }
Member Function Documentation
Phine\Phar\Signature\Algorithm\OpenSSL::getFlag ()
Returns the signature algorithm flag.
Returns
integer The signature algorithm flag.
Implements Phine\Phar\Signature\Algorithm\AlgorithmInterface.
Definition at line 34 of file OpenSSL.php.
     {
         return 0x10;
     }
Phine\Phar\Signature\Algorithm\OpenSSL::readSignature (Reader $reader)
Reads the signature from the archive file.
Parameters
Reader $reader The archive file reader.
Implements Phine\Phar\Signature\Algorithm\AlgorithmInterface.
Definition at line 42 of file OpenSSL.php.
References Phine\Phar\File\Reader\read(), and Phine\Phar\File\Reader\seek().
Referenced by Phine\Phar\Signature\Algorithm\OpenSSL\verifySignature().
     {
         $size = $this->getSize($reader);
         $reader->seek(-12 - $size, SEEK_END);
         $hash = unpack('H*', $reader->read($size));
         $hash = strtoupper($hash[1]);
         return array(
             'hash' => $hash,
             'hash_type' => 'OpenSSL'
         );
     }
Phine\Phar\Signature\Algorithm\OpenSSL::verifySignature (Reader $reader)
Verifies the signature for the archive file.
Parameters
Reader $reader The archive file reader.
Returns
boolean Returns true if verified, false if not.
Implements Phine\Phar\Signature\Algorithm\AlgorithmInterface.
Definition at line 60 of file OpenSSL.php.
References Phine\Phar\Signature\Algorithm\OpenSSL\readSignature().
     {
         $expected = $this->readSignature($reader);
         $key = $this->readPublicKey($reader);
         $data = $this->getData($reader);
         $this->resetBuffer();
         ob_start();
         $result = openssl_verify($data, pack('H*', $expected['hash']), $key);
         $error = ob_get_clean();
         if (-1 === $result) {
             throw new SignatureException(openssl_error_string());
         } elseif (!empty($error)) {
             throw new SignatureException($error);
         }
         return (1 === $result);
     }
The documentation for this class was generated from the following file:
OpenSSL.php