Phar: Phine\Phar\Manifest\FileInfo Class Reference
Phine\Phar\Manifest\FileInfo Class Reference
Manages the information of an individual manifest file entry.
Public Member Functions
__construct (Manifest $manifest, $offset, $nameSize, $name, $size, $timestamp, $compressedSize, $crc32, $flags, $metadataSize, $metadata)
Sets the information for the file.
getCompressedSize ()
Returns the compressed byte size of the file.
getCrc32 ()
Returns the CRC32 checksum for the file.
getFlags ()
Returns the bitwise flags for the file.
getManifest ()
Returns the manifest the file was read from.
getMetadata ()
Returns the metadata for the file.
getMetadataSize ()
Returns the byte size of the metadata for the file.
getName ()
Returns the name of the file.
getNameSize ()
Returns the byte size of the file name.
getOffset ()
Returns the offset for the file data.
getSize ()
Returns the uncompressed byte size of the file.
getTimestamp ()
Returns the Unix timestamp of the file.
hasMetadata ()
Checks if the file has metadata.
isCompressed ($algorithm)
Checks if the file is compressed using the specified algorithm.
Detailed Description
Manages the information of an individual manifest file entry.
Author
Kevin Herrera kevin.nosp@m.@her.nosp@m.rera..nosp@m.io
Definition at line 12 of file FileInfo.php.
Constructor & Destructor Documentation
Phine\Phar\Manifest\FileInfo::__construct (Manifest $manifest, $offset, $nameSize, $name, $size, $timestamp, $compressedSize, $crc32, $flags, $metadataSize, $metadata)
Sets the information for the file.
Parameters
Manifest $manifest The manifest the file was read from.
integer $offset The offset for the file data.
integer $nameSize The byte size of the name.
string $name The name.
integer $size The uncompressed byte size.
integer $timestamp The Unix timestamp.
integer $compressedSize The compressed byte size.
integer $crc32 The CRC32 checksum.
integer $flags The bitwise flags.
integer $metadataSize The byte size of the metadata.
mixed $metadata The metadata.
Definition at line 106 of file FileInfo.php.
       {
         $this->compressedSize = $compressedSize;
         $this->crc32 = $crc32;
         $this->flags = $flags;
         $this->manifest = $manifest;
         $this->metadata = $metadata;
         $this->metadataSize = $metadataSize;
         $this->name = $name;
         $this->nameSize = $nameSize;
         $this->offset = $offset;
         $this->size = $size;
         $this->timestamp = $timestamp;
     }
Member Function Documentation
Phine\Phar\Manifest\FileInfo::getCompressedSize ()
Returns the compressed byte size of the file.
Returns
integer The compressed size.
Definition at line 137 of file FileInfo.php.
Referenced by Phine\Phar\Extract\extractFile().
     {
         return $this->compressedSize;
     }
Phine\Phar\Manifest\FileInfo::getCrc32 ()
Returns the CRC32 checksum for the file.
Returns
integer The checksum.
Definition at line 147 of file FileInfo.php.
     {
         return $this->crc32;
     }
Phine\Phar\Manifest\FileInfo::getFlags ()
Returns the bitwise flags for the file.
Returns
integer The bitwise flags.
Definition at line 157 of file FileInfo.php.
     {
         return $this->flags;
     }
Phine\Phar\Manifest\FileInfo::getManifest ()
Returns the manifest the file was read from.
Returns
Manifest The manifest.
Definition at line 167 of file FileInfo.php.
Referenced by Phine\Phar\Extract\extractFile().
     {
         return $this->manifest;
     }
Phine\Phar\Manifest\FileInfo::getMetadata ()
Returns the metadata for the file.
Returns
mixed The metadata.
Definition at line 177 of file FileInfo.php.
     {
         return $this->metadata;
     }
Phine\Phar\Manifest\FileInfo::getMetadataSize ()
Returns the byte size of the metadata for the file.
Returns
integer The byte size of the metadata.
Definition at line 187 of file FileInfo.php.
     {
         return $this->metadataSize;
     }
Phine\Phar\Manifest\FileInfo::getName ()
Returns the name of the file.
Returns
string The name of the file.
Definition at line 197 of file FileInfo.php.
Referenced by Phine\Phar\Extract\extractFile().
     {
         return $this->name;
     }
Phine\Phar\Manifest\FileInfo::getNameSize ()
Returns the byte size of the file name.
Returns
integer The byte size of the file name.
Definition at line 207 of file FileInfo.php.
     {
         return $this->nameSize;
     }
Phine\Phar\Manifest\FileInfo::getOffset ()
Returns the offset for the file data.
Returns
integer The offset for the data.
Definition at line 217 of file FileInfo.php.
Referenced by Phine\Phar\Extract\extractFile().
     {
         return $this->offset;
     }
Phine\Phar\Manifest\FileInfo::getSize ()
Returns the uncompressed byte size of the file.
Returns
integer The uncompressed size.
Definition at line 227 of file FileInfo.php.
     {
         return $this->size;
     }
Phine\Phar\Manifest\FileInfo::getTimestamp ()
Returns the Unix timestamp of the file.
Returns
integer The Unix timestamp.
Definition at line 237 of file FileInfo.php.
     {
         return $this->timestamp;
     }
Phine\Phar\Manifest\FileInfo::hasMetadata ()
Checks if the file has metadata.
Returns
boolean If the file has metadata, true is returned. If the file does not have metadata, false is returned.
Definition at line 248 of file FileInfo.php.
     {
         return (0 < $this->metadataSize);
     }
Phine\Phar\Manifest\FileInfo::isCompressed ($algorithm)
Checks if the file is compressed using the specified algorithm.
Parameters
integer $algorithm The algorithm to check.
Returns
boolean If the file is compressed, true is returned. If the file is not compressed using the specified algorithm, false is returned.
Definition at line 262 of file FileInfo.php.
Referenced by Phine\Phar\Extract\extractFile().
     {
         return (0 < ($this->flags & $algorithm));
     }
The documentation for this class was generated from the following file:
FileInfo.php